import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import {
  Box,
  ColorSchemeProvider,
  ColorScheme,
  Container,
  MantineProvider,
  TextInput,
} from "@mantine/core";
import ShaCard from "../components/shaCard";
import Header from "../components/Header";
import HeaderMiddle from "../components/Header";
import Hero from "../components/Hero";
import Features from "../components/Features";
import ContactUs from "../components/ContactUs";
import { Footer } from "../components/Footer";
import { useState } from "react";
import { FAQ } from "../components/FAQ";
// import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [colorScheme, setColorScheme] = useState("light");
  const toggleColorScheme = (value) =>
    setColorScheme(value || (colorScheme === "dark" ? "light" : "dark"));
  return (
    <>
      <ColorSchemeProvider
        colorScheme={colorScheme}
        toggleColorScheme={toggleColorScheme}
      >
        <MantineProvider
          theme={{
            colorScheme,
            primaryColor: colorScheme === "dark" ? "cyan" : "indigo",
          }}
          withGlobalStyles
          withNormalizeCSS
        >
          <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <meta
              name='viewport'
              content='width=device-width, initial-scale=1'
            />
            <link rel='icon' href='/favicon.ico' />
          </Head>
          {/* <HeaderMiddle /> */}
          <Container
            p={0}
            // sx={{ transition: "all 2s linear" }}
          ><h1>Ratna</h1>
            <Hero />
            <Features />
            <FAQ />
            <ContactUs />
            <Footer />
          </Container>

          {/* <h1>hello world</h1> */}
          {/* <Box
        sx={{
          justifyItems: "center",
          alignItems: "center",
        }}
      >
        <Box
          sx={{
            width: "80%",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <ShaCard />
        </Box>
      </Box> */}
          {/* <TextInput placeholder='Your name' label='Full name' withAsterisk /> */}
        </MantineProvider>
      </ColorSchemeProvider>
    </>
  );
}
